# Name of website
title: David Denton

# Your name to show in the footer
author: David Denton

navbar-links:
  writing: /writing
  consulting: /consulting
  training: /training
  speaking: /speaking

avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: /assets/img/logo_white.png

social-network-links:
  feed: /feed.xml
  github: https://dentondav.id/github
  linkedin: https://dentondav.id/linkedin
  youtube: https://dentondav.id/youtube
  speakerdeck: https://dentondav.id/speakerdeck
  calendly: https://dentondav.id/calendly
  mail: mailto://hello@dentondav.id

rss-description: Musings on building software and Open Source

share-links-active:
  github: false
  youtube: false
  linkedin: false
  vk: false

url-pretty: "dentondav.id"

excerpt_length: 50

feed_show_excerpt: true

feed_show_tags: true

# --- Colours / background image --- #

#navbar-col: "#EAEAEA"
#navbar-text-col: "#404040"
#navbar-border-col: "#DDDDDD"
#page-col: "#FFFFFF"
#text-col: "#404040"
#link-col: "#008AFF"
#hover-col: "#0085A1"
#footer-col: "#EAEAEA"
#footer-text-col: "#777777"
#footer-link-col: "#404040"
navbar-col: "#1e528b"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#1e528e"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#1e528e"
hover-col: "#8b7e1e"
footer-col: "#bbbbbb"
footer-text-col: "#444444"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# --- Web Analytics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "G-7S7KT5C4VW"

# Fill in your Google Analytics ID to track your website using Google Analytics
google_analytics: "G-7S7KT5C4VW"

# Google Tag Manager ID
#gtm: ""


# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Output options (more information on Jekyll's site)
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
permalink: /posts/:year/:month/:title
paginate: 6

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - beautiful-jekyll-theme.gemspec
  - docs/
  - gradle/
  - .gradle/
  - build.gradle
  - gradlew
  - gradlew.bat
  - settings.gradle
  - serveSite.sh
  - Dockerfile

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

